[project]
name = "enterprise-d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-aw9523>=1.1.13",
    "adafruit-circuitpython-neopixel>=6.3.17",
]
